"""init

Revision ID: 0001
Revises: 
Create Date: 2025-09-03 05:14:13.120611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('onboarding_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=True)
    op.create_index(op.f('ix_app_user_id'), 'app_user', ['id'], unique=False)
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['permission.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_code'), 'permission', ['code'], unique=True)
    op.create_index(op.f('ix_permission_id'), 'permission', ['id'], unique=False)
    op.create_table('qualification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('inactive', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qualification_id'), 'qualification', ['id'], unique=False)
    op.create_table('ref_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=200), server_default='', nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ref_type_id'), 'ref_type', ['id'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_code'), 'role', ['code'], unique=True)
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('middle_name', sa.String(length=120), nullable=True),
    sa.Column('nicknames', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('dangerous', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('danger', sa.String(length=255), nullable=True),
    sa.Column('profile_pic', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_id'), 'subject', ['id'], unique=False)
    op.create_table('system_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_setting_id'), 'system_setting', ['id'], unique=False)
    op.create_table('victimology',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('victimology_category_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('follow_up', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['victimology_category_id'], ['victimology.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_victimology_id'), 'victimology', ['id'], unique=False)
    op.create_table('victimology_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_victimology_category_id'), 'victimology_category', ['id'], unique=False)
    op.create_table('app_user_role',
    sa.Column('app_user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['app_user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('app_user_id', 'role_id'),
    sa.UniqueConstraint('role_id', 'app_user_id', name='uq_app_user_role')
    )
    op.create_table('app_user_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_user_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['app_user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_session_id'), 'app_user_session', ['id'], unique=False)
    op.create_index(op.f('ix_app_user_session_jti'), 'app_user_session', ['jti'], unique=True)
    op.create_table('case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('case_number', sa.String(length=120), nullable=False),
    sa.Column('inactive', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('date_intake', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number')
    )
    op.create_index(op.f('ix_case_id'), 'case', ['id'], unique=False)
    op.create_table('ref_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=200), server_default='', nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('inactive', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('num_value', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('ref_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ref_type_id'], ['ref_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ref_value_id'), 'ref_value', ['id'], unique=False)
    op.create_index(op.f('ix_ref_value_sort_order'), 'ref_value', ['sort_order'], unique=False)
    op.create_table('rfi_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('primary_id', sa.Integer(), nullable=True),
    sa.Column('backup_id', sa.Integer(), nullable=True),
    sa.Column('inactive', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['backup_id'], ['app_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['primary_id'], ['app_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_rfi_source_id'), 'rfi_source', ['id'], unique=False)
    op.create_table('role_permission',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_table('app_user_case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_user_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['app_user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'app_user_id', name='uq_app_user_case_case_user')
    )
    op.create_index(op.f('ix_app_user_case_id'), 'app_user_case', ['id'], unique=False)
    op.create_table('case_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['ref_value.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_action_id'), 'case_action', ['id'], unique=False)
    op.create_table('case_circumstances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('date_missing', sa.Date(), nullable=True),
    sa.Column('time_missing', sa.Time(timezone=True), nullable=True),
    sa.Column('date_reported', sa.DateTime(timezone=True), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('point_last_seen', sa.Text(), nullable=True),
    sa.Column('have_id_id', sa.Integer(), nullable=True),
    sa.Column('id_taken_id', sa.Integer(), nullable=True),
    sa.Column('have_money_id', sa.Integer(), nullable=True),
    sa.Column('money_taken_id', sa.Integer(), nullable=True),
    sa.Column('have_cc_id', sa.Integer(), nullable=True),
    sa.Column('cc_taken_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_taken', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('vehicle_desc', sa.Text(), nullable=True),
    sa.Column('with_whom', sa.Text(), nullable=True),
    sa.Column('what_happened', sa.Text(), nullable=True),
    sa.Column('clothing_top', sa.Text(), nullable=True),
    sa.Column('clothing_bottom', sa.Text(), nullable=True),
    sa.Column('clothing_shoes', sa.Text(), nullable=True),
    sa.Column('clothing_outerwear', sa.Text(), nullable=True),
    sa.Column('clothing_innerwear', sa.Text(), nullable=True),
    sa.Column('bags', sa.Text(), nullable=True),
    sa.Column('other_items', sa.Text(), nullable=True),
    sa.Column('mobile_carrier_id', sa.Integer(), nullable=True),
    sa.Column('mobile_carrier_other', sa.Text(), nullable=True),
    sa.Column('voip_id', sa.Integer(), nullable=True),
    sa.Column('wifi_only', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cc_taken_id'], ['ref_value.id'], ),
    sa.ForeignKeyConstraint(['have_cc_id'], ['ref_value.id'], ),
    sa.ForeignKeyConstraint(['have_id_id'], ['ref_value.id'], ),
    sa.ForeignKeyConstraint(['have_money_id'], ['ref_value.id'], ),
    sa.ForeignKeyConstraint(['id_taken_id'], ['ref_value.id'], ),
    sa.ForeignKeyConstraint(['mobile_carrier_id'], ['ref_value.id'], ),
    sa.ForeignKeyConstraint(['money_taken_id'], ['ref_value.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['ref_value.id'], ),
    sa.ForeignKeyConstraint(['voip_id'], ['ref_value.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index(op.f('ix_case_circumstances_id'), 'case_circumstances', ['id'], unique=False)
    op.create_table('case_demographics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('age_when_missing', sa.Integer(), nullable=True),
    sa.Column('height', sa.String(length=20), nullable=True),
    sa.Column('weight', sa.String(length=20), nullable=True),
    sa.Column('hair_color', sa.String(length=20), nullable=True),
    sa.Column('hair_length', sa.String(length=20), nullable=True),
    sa.Column('eye_color', sa.String(length=20), nullable=True),
    sa.Column('identifying_marks', sa.Text(), nullable=True),
    sa.Column('sex_id', sa.Integer(), nullable=True),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['race_id'], ['ref_value.id'], ),
    sa.ForeignKeyConstraint(['sex_id'], ['ref_value.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index(op.f('ix_case_demographics_id'), 'case_demographics', ['id'], unique=False)
    op.create_table('case_disposition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('shepherds_contributed_intel', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('date_found', sa.Date(), nullable=True),
    sa.Column('scope_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('living_id', sa.Integer(), nullable=True),
    sa.Column('found_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['ref_value.id'], ),
    sa.ForeignKeyConstraint(['found_by_id'], ['ref_value.id'], ),
    sa.ForeignKeyConstraint(['living_id'], ['ref_value.id'], ),
    sa.ForeignKeyConstraint(['scope_id'], ['ref_value.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['ref_value.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index(op.f('ix_case_disposition_id'), 'case_disposition', ['id'], unique=False)
    op.create_table('case_exploitation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('exploitation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exploitation_id'], ['ref_value.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'exploitation_id', name='uq_case_exploitation_case_exploitation')
    )
    op.create_index(op.f('ix_case_exploitation_id'), 'case_exploitation', ['id'], unique=False)
    op.create_table('case_management',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('consent_sent', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('consent_returned', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('flyer_complete', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ottic', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('csec_id', sa.Integer(), nullable=True),
    sa.Column('missing_status_id', sa.Integer(), nullable=True),
    sa.Column('classification_id', sa.Integer(), nullable=True),
    sa.Column('requested_by_id', sa.Integer(), nullable=True),
    sa.Column('ncic_case_number', sa.String(length=30), nullable=True),
    sa.Column('ncmec_case_number', sa.String(length=30), nullable=True),
    sa.Column('le_case_number', sa.String(length=30), nullable=True),
    sa.Column('le_24hour_contact', sa.String(length=30), nullable=True),
    sa.Column('ss_case_number', sa.String(length=30), nullable=True),
    sa.Column('ss_24hour_contact', sa.String(length=30), nullable=True),
    sa.Column('jpo_case_number', sa.String(length=30), nullable=True),
    sa.Column('jpo_24hour_contact', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['classification_id'], ['ref_value.id'], ),
    sa.ForeignKeyConstraint(['csec_id'], ['ref_value.id'], ),
    sa.ForeignKeyConstraint(['missing_status_id'], ['ref_value.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['ref_value.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index(op.f('ix_case_management_id'), 'case_management', ['id'], unique=False)
    op.create_table('case_pattern_of_life',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('school', sa.String(length=100), nullable=True),
    sa.Column('grade', sa.String(length=20), nullable=True),
    sa.Column('missing_classes', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('school_laptop', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('school_laptop_taken', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('school_address', sa.Text(), nullable=True),
    sa.Column('employed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('employer', sa.Text(), nullable=True),
    sa.Column('work_hours', sa.Text(), nullable=True),
    sa.Column('employer_address', sa.Text(), nullable=True),
    sa.Column('confidants', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index(op.f('ix_case_pattern_of_life_id'), 'case_pattern_of_life', ['id'], unique=False)
    op.create_table('case_search_urgency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('age_id', sa.Integer(), nullable=True),
    sa.Column('physical_condition_id', sa.Integer(), nullable=True),
    sa.Column('medical_condition_id', sa.Integer(), nullable=True),
    sa.Column('personal_risk_id', sa.Integer(), nullable=True),
    sa.Column('online_risk_id', sa.Integer(), nullable=True),
    sa.Column('family_risk_id', sa.Integer(), nullable=True),
    sa.Column('behavioral_risk_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['age_id'], ['ref_value.id'], ),
    sa.ForeignKeyConstraint(['behavioral_risk_id'], ['ref_value.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['family_risk_id'], ['ref_value.id'], ),
    sa.ForeignKeyConstraint(['medical_condition_id'], ['ref_value.id'], ),
    sa.ForeignKeyConstraint(['online_risk_id'], ['ref_value.id'], ),
    sa.ForeignKeyConstraint(['personal_risk_id'], ['ref_value.id'], ),
    sa.ForeignKeyConstraint(['physical_condition_id'], ['ref_value.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index(op.f('ix_case_search_urgency_id'), 'case_search_urgency', ['id'], unique=False)
    op.create_table('case_victimology',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('victimology_id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['ref_value.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['victimology_id'], ['victimology.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'victimology_id', name='uq_case_victimology')
    )
    op.create_index(op.f('ix_case_victimology_id'), 'case_victimology', ['id'], unique=False)
    op.create_table('eod_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.Column('activity', sa.Text(), nullable=True),
    sa.Column('communication', sa.Text(), nullable=True),
    sa.Column('tomorrow_intel', sa.Text(), nullable=True),
    sa.Column('tomorrow_ops', sa.Text(), nullable=True),
    sa.Column('are_there_ministry_needs', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ministry_needs', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eod_report_id'), 'eod_report', ['id'], unique=False)
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=200), server_default='', nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('start', sa.Date(), nullable=True),
    sa.Column('end', sa.Date(), nullable=True),
    sa.Column('inactive', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['ref_value.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_id'), 'event', ['id'], unique=False)
    op.create_table('hospital_er',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('zip_code', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('inactive', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['ref_value.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospital_er_id'), 'hospital_er', ['id'], unique=False)
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['ref_value.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_organization_id'), 'organization', ['id'], unique=False)
    op.create_table('previous_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('date_ran', sa.Date(), nullable=True),
    sa.Column('point_last_seen', sa.Text(), nullable=True),
    sa.Column('accompanied_by', sa.Text(), nullable=True),
    sa.Column('found_by', sa.Text(), nullable=True),
    sa.Column('date_found', sa.Date(), nullable=True),
    sa.Column('location_found', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_previous_run_id'), 'previous_run', ['id'], unique=False)
    op.create_table('social_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('platform_other', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('investigated_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigated_id'], ['ref_value.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['ref_value.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['ref_value.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_media_id'), 'social_media', ['id'], unique=False)
    op.create_table('subject_case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('relationship_id', sa.Integer(), nullable=True),
    sa.Column('relationship_other', sa.String(length=255), nullable=True),
    sa.Column('legal_guardian', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relationship_id'], ['ref_value.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'subject_id', name='uq_case_subject')
    )
    op.create_index(op.f('ix_subject_case_id'), 'subject_case', ['id'], unique=False)
    op.create_table('event_hospital_er',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('hospital_er_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_er_id'], ['hospital_er.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'hospital_er_id', name='uq_event_hospital_er')
    )
    op.create_index(op.f('ix_event_hospital_er_id'), 'event_hospital_er', ['id'], unique=False)
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telegram', sa.String(length=50), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('profile_pic', sa.LargeBinary(), nullable=True),
    sa.Column('app_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['app_user_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_id'), 'person', ['id'], unique=False)
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('inactive', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('profile_pic', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_id'), 'team', ['id'], unique=False)
    op.create_table('intel_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('entered_by_id', sa.Integer(), nullable=False),
    sa.Column('what', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_other', sa.String(length=255), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('case_management', sa.Text(), nullable=True),
    sa.Column('reported_to', sa.Integer(), nullable=True),
    sa.Column('on_eod_report', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entered_by_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_to'], ['ref_value.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['ref_value.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intel_activity_id'), 'intel_activity', ['id'], unique=False)
    op.create_table('intel_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('entered_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entered_by_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intel_summary_id'), 'intel_summary', ['id'], unique=False)
    op.create_table('missing_flyer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missing_flyer_id'), 'missing_flyer', ['id'], unique=False)
    op.create_table('ops_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('forecast', sa.Text(), nullable=True),
    sa.Column('temperature', sa.Integer(), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('precipitation', sa.Integer(), nullable=True),
    sa.Column('uv_index', sa.Integer(), nullable=True),
    sa.Column('winds', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('op_type_id', sa.Integer(), nullable=True),
    sa.Column('op_type_other', sa.String(length=100), nullable=True),
    sa.Column('responsible_agency_id', sa.Integer(), nullable=True),
    sa.Column('subject_legal_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('vehicles', sa.Text(), nullable=True),
    sa.Column('residence_owner', sa.String(length=100), nullable=True),
    sa.Column('threat_dogs_id', sa.Integer(), nullable=True),
    sa.Column('threat_cameras_id', sa.Integer(), nullable=True),
    sa.Column('threat_weapons_id', sa.Integer(), nullable=True),
    sa.Column('threat_drugs_id', sa.Integer(), nullable=True),
    sa.Column('threat_gangs_id', sa.Integer(), nullable=True),
    sa.Column('threat_assault_id', sa.Integer(), nullable=True),
    sa.Column('threat_other', sa.Text(), nullable=True),
    sa.Column('briefing_time', sa.Time(), nullable=True),
    sa.Column('rendevouz_location', sa.Text(), nullable=True),
    sa.Column('primary_location', sa.Text(), nullable=True),
    sa.Column('comms_channel_id', sa.Integer(), nullable=True),
    sa.Column('police_phone', sa.String(length=50), server_default='911', nullable=False),
    sa.Column('ems_phone', sa.String(length=50), server_default='911', nullable=False),
    sa.Column('hospital_er_id', sa.Integer(), nullable=True),
    sa.Column('resp_contact_at_door_id', sa.Integer(), nullable=True),
    sa.Column('resp_overwatch_id', sa.Integer(), nullable=True),
    sa.Column('resp_navigation_id', sa.Integer(), nullable=True),
    sa.Column('resp_communications_id', sa.Integer(), nullable=True),
    sa.Column('resp_safety_id', sa.Integer(), nullable=True),
    sa.Column('resp_medical_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['comms_channel_id'], ['ref_value.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_er_id'], ['hospital_er.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['op_type_id'], ['ref_value.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resp_communications_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resp_contact_at_door_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resp_medical_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resp_navigation_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resp_overwatch_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resp_safety_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsible_agency_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_legal_id'], ['ref_value.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['threat_assault_id'], ['ref_value.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['threat_cameras_id'], ['ref_value.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['threat_dogs_id'], ['ref_value.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['threat_drugs_id'], ['ref_value.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['threat_gangs_id'], ['ref_value.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['threat_weapons_id'], ['ref_value.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_plan_id'), 'ops_plan', ['id'], unique=False)
    op.create_table('person_case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('relationship_id', sa.Integer(), nullable=False),
    sa.Column('relationship_other', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relationship_id'], ['ref_value.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'case_id', name='uq_person_case')
    )
    op.create_index(op.f('ix_person_case_id'), 'person_case', ['id'], unique=False)
    op.create_table('person_qualification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('qualification_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualification.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'qualification_id', name='uq_person_qualification')
    )
    op.create_index(op.f('ix_person_qualification_id'), 'person_qualification', ['id'], unique=False)
    op.create_table('person_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('team_role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_role_id'], ['ref_value.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'team_id', name='uq_person_team')
    )
    op.create_index(op.f('ix_person_team_id'), 'person_team', ['id'], unique=False)
    op.create_table('rfi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('rfi_source_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('responded_by_id', sa.Integer(), nullable=True),
    sa.Column('results', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responded_by_id'], ['person.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rfi_source_id'], ['rfi_source.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfi_id'), 'rfi', ['id'], unique=False)
    op.create_table('social_media_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('social_media_id', sa.Integer(), nullable=False),
    sa.Column('alias_status_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.Text(), nullable=True),
    sa.Column('alias_owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alias_owner_id'], ['person.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['alias_status_id'], ['ref_value.id'], ),
    sa.ForeignKeyConstraint(['social_media_id'], ['case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_media_alias_id'), 'social_media_alias', ['id'], unique=False)
    op.create_table('team_case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_case_id'), 'team_case', ['id'], unique=False)
    op.create_table('timeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('entered_by_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('type_other', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('where', sa.Text(), nullable=True),
    sa.Column('who_id', sa.Integer(), nullable=True),
    sa.Column('questions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entered_by_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_id'], ['ref_value.id'], ),
    sa.ForeignKeyConstraint(['who_id'], ['person.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_id'), 'timeline', ['id'], unique=False)
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rfi_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rfi_id'], ['rfi.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_id'), 'file', ['id'], unique=False)
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(length=255), nullable=True),
    sa.Column('where', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('storage_slug', sa.String(length=100), nullable=True),
    sa.Column('rfi_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['person.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rfi_id'], ['rfi.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_id'), 'image', ['id'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('reply_to_id', sa.Integer(), nullable=True),
    sa.Column('rfi_id', sa.Integer(), nullable=True),
    sa.Column('intel_summary_id', sa.Integer(), nullable=True),
    sa.Column('ops_plan_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['intel_summary_id'], ['intel_summary.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ops_plan_id'], ['ops_plan.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_to_id'], ['message.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rfi_id'], ['rfi.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_id'), 'message', ['id'], unique=False)
    op.create_table('ops_plan_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ops_plan_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_other', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ops_plan_id'], ['ops_plan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['ref_value.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ops_plan_id', 'person_id', name='uq_ops_plan_person')
    )
    op.create_index(op.f('ix_ops_plan_assignment_id'), 'ops_plan_assignment', ['id'], unique=False)
    op.create_table('image_person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_person_id'), 'image_person', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_person_id'), table_name='image_person')
    op.drop_table('image_person')
    op.drop_index(op.f('ix_ops_plan_assignment_id'), table_name='ops_plan_assignment')
    op.drop_table('ops_plan_assignment')
    op.drop_index(op.f('ix_message_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_image_id'), table_name='image')
    op.drop_table('image')
    op.drop_index(op.f('ix_file_id'), table_name='file')
    op.drop_table('file')
    op.drop_index(op.f('ix_timeline_id'), table_name='timeline')
    op.drop_table('timeline')
    op.drop_index(op.f('ix_team_case_id'), table_name='team_case')
    op.drop_table('team_case')
    op.drop_index(op.f('ix_social_media_alias_id'), table_name='social_media_alias')
    op.drop_table('social_media_alias')
    op.drop_index(op.f('ix_rfi_id'), table_name='rfi')
    op.drop_table('rfi')
    op.drop_index(op.f('ix_person_team_id'), table_name='person_team')
    op.drop_table('person_team')
    op.drop_index(op.f('ix_person_qualification_id'), table_name='person_qualification')
    op.drop_table('person_qualification')
    op.drop_index(op.f('ix_person_case_id'), table_name='person_case')
    op.drop_table('person_case')
    op.drop_index(op.f('ix_ops_plan_id'), table_name='ops_plan')
    op.drop_table('ops_plan')
    op.drop_index(op.f('ix_missing_flyer_id'), table_name='missing_flyer')
    op.drop_table('missing_flyer')
    op.drop_index(op.f('ix_intel_summary_id'), table_name='intel_summary')
    op.drop_table('intel_summary')
    op.drop_index(op.f('ix_intel_activity_id'), table_name='intel_activity')
    op.drop_table('intel_activity')
    op.drop_index(op.f('ix_team_id'), table_name='team')
    op.drop_table('team')
    op.drop_index(op.f('ix_person_id'), table_name='person')
    op.drop_table('person')
    op.drop_index(op.f('ix_event_hospital_er_id'), table_name='event_hospital_er')
    op.drop_table('event_hospital_er')
    op.drop_index(op.f('ix_subject_case_id'), table_name='subject_case')
    op.drop_table('subject_case')
    op.drop_index(op.f('ix_social_media_id'), table_name='social_media')
    op.drop_table('social_media')
    op.drop_index(op.f('ix_previous_run_id'), table_name='previous_run')
    op.drop_table('previous_run')
    op.drop_index(op.f('ix_organization_id'), table_name='organization')
    op.drop_table('organization')
    op.drop_index(op.f('ix_hospital_er_id'), table_name='hospital_er')
    op.drop_table('hospital_er')
    op.drop_index(op.f('ix_event_id'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_eod_report_id'), table_name='eod_report')
    op.drop_table('eod_report')
    op.drop_index(op.f('ix_case_victimology_id'), table_name='case_victimology')
    op.drop_table('case_victimology')
    op.drop_index(op.f('ix_case_search_urgency_id'), table_name='case_search_urgency')
    op.drop_table('case_search_urgency')
    op.drop_index(op.f('ix_case_pattern_of_life_id'), table_name='case_pattern_of_life')
    op.drop_table('case_pattern_of_life')
    op.drop_index(op.f('ix_case_management_id'), table_name='case_management')
    op.drop_table('case_management')
    op.drop_index(op.f('ix_case_exploitation_id'), table_name='case_exploitation')
    op.drop_table('case_exploitation')
    op.drop_index(op.f('ix_case_disposition_id'), table_name='case_disposition')
    op.drop_table('case_disposition')
    op.drop_index(op.f('ix_case_demographics_id'), table_name='case_demographics')
    op.drop_table('case_demographics')
    op.drop_index(op.f('ix_case_circumstances_id'), table_name='case_circumstances')
    op.drop_table('case_circumstances')
    op.drop_index(op.f('ix_case_action_id'), table_name='case_action')
    op.drop_table('case_action')
    op.drop_index(op.f('ix_app_user_case_id'), table_name='app_user_case')
    op.drop_table('app_user_case')
    op.drop_table('role_permission')
    op.drop_index(op.f('ix_rfi_source_id'), table_name='rfi_source')
    op.drop_table('rfi_source')
    op.drop_index(op.f('ix_ref_value_sort_order'), table_name='ref_value')
    op.drop_index(op.f('ix_ref_value_id'), table_name='ref_value')
    op.drop_table('ref_value')
    op.drop_index(op.f('ix_case_id'), table_name='case')
    op.drop_table('case')
    op.drop_index(op.f('ix_app_user_session_jti'), table_name='app_user_session')
    op.drop_index(op.f('ix_app_user_session_id'), table_name='app_user_session')
    op.drop_table('app_user_session')
    op.drop_table('app_user_role')
    op.drop_index(op.f('ix_victimology_category_id'), table_name='victimology_category')
    op.drop_table('victimology_category')
    op.drop_index(op.f('ix_victimology_id'), table_name='victimology')
    op.drop_table('victimology')
    op.drop_index(op.f('ix_system_setting_id'), table_name='system_setting')
    op.drop_table('system_setting')
    op.drop_index(op.f('ix_subject_id'), table_name='subject')
    op.drop_table('subject')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_index(op.f('ix_role_code'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_ref_type_id'), table_name='ref_type')
    op.drop_table('ref_type')
    op.drop_index(op.f('ix_qualification_id'), table_name='qualification')
    op.drop_table('qualification')
    op.drop_index(op.f('ix_permission_id'), table_name='permission')
    op.drop_index(op.f('ix_permission_code'), table_name='permission')
    op.drop_table('permission')
    op.drop_index(op.f('ix_app_user_id'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###
