"""Case Tables

Revision ID: 0004
Revises: 0003
Create Date: 2025-08-19 18:25:19.423461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.db.base import seed

# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ref_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ref_activity_id'), 'ref_activity', ['id'], unique=False)
    op.create_table('ref_case_classification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ref_case_classification_id'), 'ref_case_classification', ['id'], unique=False)
    op.create_table('ref_file_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ref_file_type_id'), 'ref_file_type', ['id'], unique=False)
    op.create_table('ref_relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ref_relation_id'), 'ref_relation', ['id'], unique=False)
    op.create_table('ref_scope',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ref_scope_id'), 'ref_scope', ['id'], unique=False)
    op.create_table('ref_sm_platform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ref_sm_platform_id'), 'ref_sm_platform', ['id'], unique=False)
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_id'), 'subject', ['id'], unique=False)
    op.create_table('case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('date_missing', sa.Date(), nullable=True),
    sa.Column('time_missing', sa.Time(), nullable=True),
    sa.Column('number', sa.String(length=120), nullable=True),
    sa.Column('missing_from_state_id', sa.Integer(), nullable=True),
    sa.Column('inactive', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['missing_from_state_id'], ['ref_state.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_id'), 'case', ['id'], unique=False)
    op.create_table('app_user_case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_user_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['app_user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_case_id'), 'app_user_case', ['id'], unique=False)
    op.create_table('team_case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_case_id'), 'team_case', ['id'], unique=False)
    op.add_column('permission', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'permission', 'permission', ['parent_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_qualification_code'), table_name='qualification')
    op.drop_index(op.f('ix_team_name'), table_name='team')
    op.drop_index(op.f('ix_team_role_code'), table_name='team_role')
    # ### end Alembic commands ###

    seed("ref_scope", [{"name" : "National", "code": "NAT"},
                       {"name" : "Regional", "code": "RGN"},
                       {"name" : "TBS", "code": "TBS"}])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_team_role_code'), 'team_role', ['code'], unique=True)
    op.create_index(op.f('ix_team_name'), 'team', ['name'], unique=False)
    op.create_index(op.f('ix_qualification_code'), 'qualification', ['code'], unique=False)
    op.drop_constraint(None, 'permission', type_='foreignkey')
    op.drop_column('permission', 'parent_id')
    op.drop_index(op.f('ix_team_case_id'), table_name='team_case')
    op.drop_table('team_case')
    op.drop_index(op.f('ix_app_user_case_id'), table_name='app_user_case')
    op.drop_table('app_user_case')
    op.drop_index(op.f('ix_case_id'), table_name='case')
    op.drop_table('case')
    op.drop_index(op.f('ix_subject_id'), table_name='subject')
    op.drop_table('subject')
    op.drop_index(op.f('ix_ref_sm_platform_id'), table_name='ref_sm_platform')
    op.drop_table('ref_sm_platform')
    op.drop_index(op.f('ix_ref_scope_id'), table_name='ref_scope')
    op.drop_table('ref_scope')
    op.drop_index(op.f('ix_ref_relation_id'), table_name='ref_relation')
    op.drop_table('ref_relation')
    op.drop_index(op.f('ix_ref_file_type_id'), table_name='ref_file_type')
    op.drop_table('ref_file_type')
    op.drop_index(op.f('ix_ref_case_classification_id'), table_name='ref_case_classification')
    op.drop_table('ref_case_classification')
    op.drop_index(op.f('ix_ref_activity_id'), table_name='ref_activity')
    op.drop_table('ref_activity')
    # ### end Alembic commands ###
