"""Cascade delete for app_user_session

Revision ID: 9441ccec842c
Revises: c0c8f5d65dbd
Create Date: 2025-08-15 07:41:30.593271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9441ccec842c'
down_revision: Union[str, Sequence[str], None] = 'c0c8f5d65dbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('app_user_session_app_user_id_fkey'), 'app_user_session', type_='foreignkey')
    op.create_foreign_key(None, 'app_user_session', 'app_user', ['app_user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'app_user_session', type_='foreignkey')
    op.create_foreign_key(op.f('app_user_session_app_user_id_fkey'), 'app_user_session', 'app_user', ['app_user_id'], ['id'])
    # ### end Alembic commands ###
